# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-09 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('varify_password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('arival_time', models.CharField(max_length=30)),
                ('depetrure_time', models.CharField(max_length=30)),
                ('platform', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pnr', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=30)),
                ('coach_no', models.CharField(max_length=10)),
                ('seat_no', models.IntegerField()),
                ('from_station', models.CharField(max_length=30)),
                ('to_station', models.CharField(max_length=30)),
                ('fair', models.IntegerField()),
                ('d_o_j', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='train_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Train'),
        ),
        migrations.AddField(
            model_name='station',
            name='train_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Train'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Register'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Ticket'),
        ),
    ]
