# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-10 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
