# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-12 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190110_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='varify_password',
        ),
    ]
