# Generated by Django 2.0.7 on 2019-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_register_varify_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='arival_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='depetrure_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
