# Generated by Django 2.0.7 on 2019-01-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190127_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='arival_time',
        ),
        migrations.RemoveField(
            model_name='station',
            name='depetrure_time',
        ),
    ]
