# Generated by Django 2.0.7 on 2019-02-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20190127_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='pnr',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
