# Generated by Django 2.0.7 on 2019-02-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190206_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='coach_A',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='coach_B',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='fair_A',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='fair_B',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='fair_general',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='general',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
