# Generated by Django 2.0.7 on 2019-02-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20190207_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='train_no',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
