# Generated by Django 2.0.7 on 2019-02-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_app', '0008_auto_20190210_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='F', max_length=1)),
                ('status', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pnr', models.IntegerField(primary_key=True, serialize=False)),
                ('coach', models.CharField(choices=[('A', 'first class'), ('B', 'Second class'), ('G', 'general')], default='G', max_length=1)),
                ('seat_no', models.IntegerField()),
                ('from_station', models.CharField(max_length=30)),
                ('to_station', models.CharField(max_length=30)),
                ('fair', models.IntegerField()),
                ('d_o_j', models.DateField()),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Train')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
