# Generated by Django 2.0.7 on 2019-02-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
