# Generated by Django 2.0.7 on 2019-02-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190212_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fair',
            field=models.IntegerField(null=True),
        ),
    ]
