# Generated by Django 2.0.7 on 2019-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190212_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
