# Generated by Django 2.0.7 on 2019-02-13 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190212_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='seat_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='status',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
